use_frameworks!

target 'VISPER-Wireframe_Example' do
  pod 'VISPER-Wireframe', :path => '../'
end

target 'VISPER-Wireframe_Tests' do
    pod 'VISPER-Wireframe', :path => '../'
    pod 'VISPER-Wireframe-Protocols', :path => '../'
    pod 'VISPER-Wireframe-UIViewController', :path => '../'
end


